- name: working on fiters
  hosts: localhost
  become: yes
  vars:
    Name: Srivani
    website: https://www.joindevops.com/
    Greeting: Hello Porter , How are you ?
  tasks:
  - name: converting upper case to lowercase
    ansible.builtin.debug:
      msg: "{{ Name | upper }}"

  - name: Printing Undefined variable
    ansible.builtin.debug:
      msg: "{{ course | default('devops') }}"     # now devops will be given to course\

  - name: Extract host name
    ansible.builtin.debug:
      msg: "{{ website | urlsplit('hostname') }}" 

  - name: Extract host name
    ansible.builtin.debug:
      msg: "{{ Greeting | split(',') }}"       